source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'action_args'
gem 'coffee-rails'
gem 'haml-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'neo4j'
gem 'quiet_assets'
gem 'rails-i18n'
gem 'sass-rails'
gem 'uglifier'

group :development, :test do
  gem 'byebug'
  gem 'erb2haml'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'tapp'
end

group :development do
  gem 'spring'
  gem 'web-console'
end

